### ISSUE TITLE
More user-friendlyness.

### ISSUE THREAD

**Issue by Ovyerus** [sr229/Tsuiga#2]
- [x] Convert some snek_case properties to camelCase,
- [x] Add models for Users and Bots for documentation, and so users can easily check return values.
- [x] Properly parse errors from the API.

1.0.0 Should be good to go after this, proper tests, and documentation.

**Comment by sr229** [comment]
I don't think this is required, we're just wrapping around the official API. We don't really need to do shiz

**Comment by sr229** [comment]
As for the error-handling, I don't think we need it at all.

**Comment by Ovyerus** [comment]
Gotta have some advantage over the default wrapper /shrug
